"use client";

import type { WallChromeHeaderProps, WallInCanvasChromeProps } from "@/components/wall/chrome/WallChromeShell";
import type { WallSpatialViewProps } from "@/components/wall/spatial/WallSpatialView";

export type UseWallSpatialBindingsOptions = Omit<WallSpatialViewProps, "chromeSlot"> &
  WallChromeHeaderProps &
  WallInCanvasChromeProps;

export type UseWallSpatialBindingsResult = {
  showChromeHeader: boolean;
  spatialView: Omit<WallSpatialViewProps, "chromeSlot">;
  chromeHeader: WallChromeHeaderProps;
  inCanvasChrome: WallInCanvasChromeProps;
};

const pickSpatialView = (
  options: UseWallSpatialBindingsOptions,
): Omit<WallSpatialViewProps, "chromeSlot"> => ({
  containerRef: options.containerRef,
  stageRef: options.stageRef,
  noteTransformerRef: options.noteTransformerRef,
  zoneTransformerRef: options.zoneTransformerRef,
  noteNodeRefs: options.noteNodeRefs,
  zoneNodeRefs: options.zoneNodeRefs,
  dragSelectionStartRef: options.dragSelectionStartRef,
  dragAnchorRef: options.dragAnchorRef,
  dragSingleStartRef: options.dragSingleStartRef,
  wallInlineVideoRef: options.wallInlineVideoRef,
  hydrated: options.hydrated,
  readingMode: options.readingMode,
  timelineViewActive: options.timelineViewActive,
  isFocusMode: options.isFocusMode,
  isImageDragOver: options.isImageDragOver,
  isTimeLocked: options.isTimeLocked,
  isSpaceDown: options.isSpaceDown,
  isMiddleDragging: options.isMiddleDragging,
  isLeftCanvasDragging: options.isLeftCanvasDragging,
  boxSelectMode: options.boxSelectMode,
  camera: options.camera,
  viewport: options.viewport,
  spatialPrefs: options.spatialPrefs,
  layoutPrefs: options.layoutPrefs,
  setCamera: options.setCamera,
  setIsMiddleDragging: options.setIsMiddleDragging,
  setIsLeftCanvasDragging: options.setIsLeftCanvasDragging,
  setIsImageDragOver: options.setIsImageDragOver,
  setGuideLines: options.setGuideLines,
  setFocusedNoteId: options.setFocusedNoteId,
  setInlinePlayingVideoNoteId: options.setInlinePlayingVideoNoteId,
  setEditing: options.setEditing,
  setHoveredNoteId: options.setHoveredNoteId,
  setDraggingNoteId: options.setDraggingNoteId,
  setResizingNoteDrafts: options.setResizingNoteDrafts,
  setLinkMenu: options.setLinkMenu,
  selectionBox: options.selectionBox,
  setSelectionBox: options.setSelectionBox,
  guideLines: options.guideLines,
  showHeatmap: options.showHeatmap,
  heatmapReferenceTs: options.heatmapReferenceTs,
  layerVisibleNotes: options.layerVisibleNotes,
  layerVisibleZones: options.layerVisibleZones,
  layerVisibleLinks: options.layerVisibleLinks,
  layerRenderDetailLevel: options.layerRenderDetailLevel,
  layerRenderBudget: options.layerRenderBudget,
  resolvedWallAssets: options.resolvedWallAssets,
  activeSelectedNoteIds: options.activeSelectedNoteIds,
  displayNotesById: options.displayNotesById,
  renderSnapshotNotes: options.renderSnapshotNotes,
  renderPathLinkIds: options.renderPathLinkIds,
  clusterBounds: options.clusterBounds,
  autoTagGroups: options.autoTagGroups,
  autoTagLabelLayout: options.autoTagLabelLayout,
  showAutoTagGroups: options.showAutoTagGroups,
  wikiLinksByNoteId: options.wikiLinksByNoteId,
  resizingNoteDrafts: options.resizingNoteDrafts,
  hoveredNoteId: options.hoveredNoteId,
  draggingNoteId: options.draggingNoteId,
  inlinePlayingVideoNoteId: options.inlinePlayingVideoNoteId,
  inlinePlayingVideoScreenRect: options.inlinePlayingVideoScreenRect,
  playingAudioNoteId: options.playingAudioNoteId,
  playingAudioCurrentTimeSeconds: options.playingAudioCurrentTimeSeconds,
  playingAudioDurationSeconds: options.playingAudioDurationSeconds,
  selectedNoteId: options.selectedNoteId,
  selectedLinkId: options.selectedLinkId,
  selectedZoneId: options.selectedZoneId,
  flashNoteId: options.flashNoteId,
  linkingFromNoteId: options.linkingFromNoteId,
  linkType: options.linkType,
  editingId: options.editingId,
  stopCameraAnimation: options.stopCameraAnimation,
  resetSelection: options.resetSelection,
  clearNoteSelection: options.clearNoteSelection,
  finalizeBoxSelection: options.finalizeBoxSelection,
  findNoteAtWorldPoint: options.findNoteAtWorldPoint,
  handleImageFileInsert: options.handleImageFileInsert,
  syncPrimarySelection: options.syncPrimarySelection,
  selectSingleNote: options.selectSingleNote,
  toggleSelectNote: options.toggleSelectNote,
  selectLink: options.selectLink,
  selectZone: options.selectZone,
  selectGroup: options.selectGroup,
  setLinkingFromNote: options.setLinkingFromNote,
  openEditor: options.openEditor,
  openImageInsert: options.openImageInsert,
  resolveSnappedPosition: options.resolveSnappedPosition,
  runHistoryGroup: options.runHistoryGroup,
  moveNote: options.moveNote,
  updateNote: options.updateNote,
  moveZone: options.moveZone,
  updateZone: options.updateZone,
  createLink: options.createLink,
  toggleVocabularyFlip: options.toggleVocabularyFlip,
  duplicateNoteAt: options.duplicateNoteAt,
  focusNote: options.focusNote,
  openBookmarkUrl: options.openBookmarkUrl,
  downloadFileNote: options.downloadFileNote,
  toggleAudioNotePlayback: options.toggleAudioNotePlayback,
  openAudioNote: options.openAudioNote,
  downloadAudioNote: options.downloadAudioNote,
  toggleInlineVideoPlayback: options.toggleInlineVideoPlayback,
  downloadVideoNote: options.downloadVideoNote,
  showClusters: options.showClusters,
});

const pickChromeHeader = (options: UseWallSpatialBindingsOptions): WallChromeHeaderProps => ({
  presentationMode: options.presentationMode,
  publishedReadOnly: options.publishedReadOnly,
  timelineViewActive: options.timelineViewActive,
  layoutPrefs: options.layoutPrefs,
  leftPanelOpen: options.leftPanelOpen,
  rightPanelOpen: options.rightPanelOpen,
  quickCaptureOpen: options.quickCaptureOpen,
  isTimeLocked: options.isTimeLocked,
  hasContextActions: options.hasContextActions,
  showContextColor: options.showContextColor,
  toolbarSurface: options.toolbarSurface,
  toolbarLabel: options.toolbarLabel,
  toolbarDivider: options.toolbarDivider,
  selectedNotes: options.selectedNotes,
  selectedNote: options.selectedNote,
  uiLastColor: options.uiLastColor,
  statusMessage: options.statusMessage,
  userEmail: options.userEmail,
  userProfile: options.userProfile,
  cloudWallId: options.cloudWallId,
  isSyncing: options.isSyncing,
  localSaveState: options.localSaveState,
  hasPendingSync: options.hasPendingSync,
  lastSyncedAt: options.lastSyncedAt,
  syncError: options.syncError,
  onToggleLeftPanel: options.onToggleLeftPanel,
  onToggleRightPanel: options.onToggleRightPanel,
  onOpenCommandPalette: options.onOpenCommandPalette,
  onToggleQuickCapture: options.onToggleQuickCapture,
  onToggleTimelineView: options.onToggleTimelineView,
  onTogglePresentationMode: options.onTogglePresentationMode,
  onOpenShortcuts: options.onOpenShortcuts,
  onOpenHelp: options.onOpenHelp,
  onOpenSettings: options.onOpenSettings,
  onApplyColorToSelection: options.onApplyColorToSelection,
  onSyncNow: options.onSyncNow,
});

const pickInCanvasChrome = (options: UseWallSpatialBindingsOptions): WallInCanvasChromeProps => ({
  readingMode: options.readingMode,
  timelineViewActive: options.timelineViewActive,
  isChromeHidden: options.isChromeHidden,
  publishedReadOnly: options.publishedReadOnly,
  layoutPrefs: options.layoutPrefs,
  leftPanelOpen: options.leftPanelOpen,
  hasNoteSelection: options.hasNoteSelection,
  isTimeLocked: options.isTimeLocked,
  selectedNoteId: options.selectedNoteId,
  linkingFromNoteId: options.linkingFromNoteId,
  linkType: options.linkType,
  showClusters: options.showClusters,
  boxSelectMode: options.boxSelectMode,
  spatialPrefs: options.spatialPrefs,
  controlsMode: options.controlsMode,
  toolbarBtn: options.toolbarBtn,
  toolbarBtnPrimary: options.toolbarBtnPrimary,
  toolbarBtnActive: options.toolbarBtnActive,
  toolbarSelect: options.toolbarSelect,
  tourCoachmark: options.tourCoachmark,
  onTourNext: options.onTourNext,
  onTourSkip: options.onTourSkip,
  onTourDismissTip: options.onTourDismissTip,
  onTourDismissComplete: options.onTourDismissComplete,
  notes: options.notes,
  visibleNotes: options.visibleNotes,
  recallQuery: options.recallQuery,
  commandPaletteCommands: options.commandPaletteCommands,
  availableRecallTags: options.availableRecallTags,
  cloudWallId: options.cloudWallId,
  isSyncing: options.isSyncing,
  hasPendingSync: options.hasPendingSync,
  syncError: options.syncError,
  isSearchOpen: options.isSearchOpen,
  setLeftPanelOpen: options.setLeftPanelOpen,
  setBoxSelectMode: options.setBoxSelectMode,
  setSpatialPrefs: options.setSpatialPrefs,
  setLinkingFromNote: options.setLinkingFromNote,
  setLinkType: options.setLinkType,
  setShowClusters: options.setShowClusters,
  setSearchOpenTracked: options.setSearchOpenTracked,
  setRecallQuery: options.setRecallQuery,
  setTimelineViewActive: options.setTimelineViewActive,
  syncPrimarySelection: options.syncPrimarySelection,
  selectNote: options.selectNote,
  clearNoteSelection: options.clearNoteSelection,
  focusNote: options.focusNote,
  revealNoteFromTimeline: options.revealNoteFromTimeline,
  makeNoteAtViewportCenter: options.makeNoteAtViewportCenter,
  makeCanonNoteAtViewportCenter: options.makeCanonNoteAtViewportCenter,
  makeJournalNoteAtViewportCenter: options.makeJournalNoteAtViewportCenter,
  makeQuoteNoteAtViewportCenter: options.makeQuoteNoteAtViewportCenter,
  makeCodeNoteAtViewportCenter: options.makeCodeNoteAtViewportCenter,
  makeWebBookmarkNoteAtViewportCenter: options.makeWebBookmarkNoteAtViewportCenter,
  makeImageNoteAtViewportCenter: options.makeImageNoteAtViewportCenter,
  makeFileNoteAtViewportCenter: options.makeFileNoteAtViewportCenter,
  makeAudioNoteAtViewportCenter: options.makeAudioNoteAtViewportCenter,
  makeVideoNoteAtViewportCenter: options.makeVideoNoteAtViewportCenter,
  makeEisenhowerNoteAtViewportCenter: options.makeEisenhowerNoteAtViewportCenter,
  makeWordNoteAtViewportCenter: options.makeWordNoteAtViewportCenter,
  makeZoneAtViewportCenter: options.makeZoneAtViewportCenter,
  openFileConversion: options.openFileConversion,
});

export const useWallSpatialBindings = (
  options: UseWallSpatialBindingsOptions,
): UseWallSpatialBindingsResult => ({
  showChromeHeader: !options.readingMode && !options.timelineViewActive,
  spatialView: pickSpatialView(options),
  chromeHeader: pickChromeHeader(options),
  inCanvasChrome: pickInCanvasChrome(options),
});
