import type { Note } from "@/features/wall/types";

export const wallNoteViewModelFixtures = {
  standard: {
    id: "standard",
    text: "[[Project Atlas]]\nShip the first slice",
    tags: ["roadmap"],
    x: 0,
    y: 0,
    w: 240,
    h: 160,
    color: "#FFFFFF",
    createdAt: 0,
    updatedAt: 0,
  } satisfies Note,
  private: {
    id: "private",
    text: "secret payload",
    tags: [],
    x: 0,
    y: 0,
    w: 240,
    h: 160,
    color: "#FFFFFF",
    createdAt: 0,
    updatedAt: 0,
    privateNote: {
      version: 1,
      salt: "salt",
      iv: "iv",
      ciphertext: "cipher",
      protectedAt: 0,
      updatedAt: 0,
    },
  } satisfies Note,
  file: {
    id: "file",
    noteKind: "file",
    text: "Quarterly review\nattached below",
    tags: ["file"],
    x: 0,
    y: 0,
    w: 320,
    h: 112,
    color: "#FFFFFF",
    createdAt: 0,
    updatedAt: 0,
    file: {
      source: "upload",
      name: "quarterly-report.pdf",
      url: "data:application/pdf;base64,AA==",
      mimeType: "application/pdf",
      sizeBytes: 2_048_000,
    },
  } satisfies Note,
  audio: {
    id: "audio",
    noteKind: "audio",
    text: "",
    tags: ["audio"],
    x: 0,
    y: 0,
    w: 428,
    h: 248,
    color: "#FFFFFF",
    createdAt: 0,
    updatedAt: 0,
    audio: {
      source: "upload",
      name: "Ambient Texture.mp3",
      url: "data:audio/mpeg;base64,AA==",
      mimeType: "audio/mpeg",
      durationSeconds: 186,
    },
  } satisfies Note,
  video: {
    id: "video",
    noteKind: "video",
    text: "",
    tags: ["video"],
    x: 0,
    y: 0,
    w: 480,
    h: 320,
    color: "#FFFFFF",
    createdAt: 0,
    updatedAt: 0,
    video: {
      source: "link",
      name: "Launch recap.mp4",
      url: "https://example.com/launch.mp4",
      mimeType: "video/mp4",
      durationSeconds: 420,
    },
  } satisfies Note,
  image: {
    id: "image",
    noteKind: "image",
    text: "Morning light over the studio",
    tags: ["image"],
    x: 0,
    y: 0,
    w: 360,
    h: 420,
    color: "#FFFFFF",
    createdAt: 0,
    updatedAt: 0,
    file: {
      source: "upload",
      name: "studio.jpg",
      url: "data:image/jpeg;base64,AA==",
      mimeType: "image/jpeg",
      sizeBytes: 512_000,
    },
  } satisfies Note,
  bookmark: {
    id: "bookmark",
    noteKind: "web-bookmark",
    text: "",
    tags: ["bookmark"],
    x: 0,
    y: 0,
    w: 560,
    h: 126,
    color: "#FFFFFF",
    createdAt: 0,
    updatedAt: 0,
    bookmark: {
      url: "https://example.com",
      normalizedUrl: "https://example.com",
      status: "ready",
      metadata: {
        url: "https://example.com",
        finalUrl: "https://example.com",
        title: "Example Article",
        description: "A useful article",
        siteName: "Example",
        domain: "example.com",
        kind: "article",
      },
    },
  } satisfies Note,
  journal: {
    id: "journal",
    noteKind: "journal",
    text: "Dear Wall,\nThis is the second line of the journal entry.",
    tags: ["journal"],
    x: 0,
    y: 0,
    w: 280,
    h: 200,
    color: "#FFFFFF",
    createdAt: Date.UTC(2026, 2, 16, 18, 0, 0),
    updatedAt: 0,
  } satisfies Note,
} as const;
