alter table public.walls
  add column if not exists sync_version bigint not null default 0;

alter table public.notes
  add column if not exists revision bigint not null default 0;

alter table public.zones
  add column if not exists revision bigint not null default 0;

alter table public.zone_groups
  add column if not exists revision bigint not null default 0;

alter table public.note_groups
  add column if not exists revision bigint not null default 0;

alter table public.links
  add column if not exists revision bigint not null default 0;

create table if not exists public.wall_changes (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  wall_id uuid not null references public.walls(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  revision bigint not null,
  deleted boolean not null default false,
  payload jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists idx_wall_changes_owner_wall_id
  on public.wall_changes(owner_id, wall_id, id asc);

create index if not exists idx_wall_changes_owner_wall_entity
  on public.wall_changes(owner_id, wall_id, entity_type, entity_id, id desc);

alter table public.wall_changes enable row level security;

drop policy if exists wall_changes_select_own on public.wall_changes;
create policy wall_changes_select_own on public.wall_changes for select using (owner_id = auth.uid());

drop policy if exists wall_changes_insert_own on public.wall_changes;
create policy wall_changes_insert_own on public.wall_changes for insert with check (owner_id = auth.uid());

drop policy if exists wall_changes_update_own on public.wall_changes;
create policy wall_changes_update_own on public.wall_changes for update using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists wall_changes_delete_own on public.wall_changes;
create policy wall_changes_delete_own on public.wall_changes for delete using (owner_id = auth.uid());
